### PR TITLE
edited readme

### PR DESCRIPTION
**Pull request by vedantdadurwade**

### CODE REVIEW

**Review by Amey-Chaudhari — CHANGES_REQUESTED** [review]
change opencv_1fsf to hello world

**Comment by Amey-Chaudhari** [comment]
waiting

**Review by Amey-Chaudhari — CHANGES_REQUESTED** [review]
try a paragraph

**Comment by vedantdadurwade** [comment]
ok

**Review by Amey-Chaudhari — APPROVED** [review]

**Review by Amey-Chaudhari — APPROVED** [review]

**Comment by Amey-Chaudhari** [comment]
nice
sunflowernew

**Pull request closed without merging**
